// try catch

const n_uno = 10;
const n_tres  = 30;

console.log(n_uno);

try {
    console.log(n_dos);
} catch (error) {
    console.log(error);
}

console.log(n_tres);
